<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta charset="utf-8" />
	<title>Congratulations LH Framework Successfully Installed</title>
</head>

<body>
	<h2>If you see this in your web browser that's mean LH Framework successfully installed in your web server.</h2>
	<p style="font-size: 1.2em;">
		Don't worry although the HTML appearance is somewhat plain BUT LH Framework will enhance your web application.
	</p>
</body>
</html>